Feat/auth middleware
Extheoisah/Mava pull request #45
Opened 2023-09-07 00:54 UTC by tobi-bams

2023-09-07 10:24 UTC, Extheoisah requested changes

2023-09-07 10:24 UTC, Extheoisah commented on src/server/middlewares/auth.ts
> +    const user = (await Account.findOne({
finding an account should be the service layer. You can create an `AccountRepository` function in `services/Account` that receives an `id` and returns the user account.

2023-09-07 10:24 UTC, Extheoisah commented on src/server/middlewares/auth.ts
> +    const user = (await Account.findOne({
same here. `AccountRepositoty`

2023-09-15 11:29 UTC, tobi-bams commented on src/domain/shared/primitives.ts
> +export interface JwtPayload {
could this be in the `domain/authentication` part??

2023-09-15 11:56 UTC, tobi-bams commented on src/server/middlewares/auth.ts
> +      return { success: true, msg: "invalid token" }
Seem's I am not getting you.

I don't want to throw an error, I just want to return an error

2023-09-26 08:43 UTC, Extheoisah approved these changes

2023-10-02 11:01 UTC, merged